version: '3.8'

services:
  dev:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ..:/workspace:cached
      - /var/run/docker.sock:/var/run/docker.sock
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0
    privileged: true
    network_mode: host
    environment:
      - PYTHONPATH=/workspace
      - PYTHONUNBUFFERED=1
    working_dir: /workspace
    command: sleep infinity